### ISSUE TITLE
listing more than 3 portfolio items

### ISSUE THREAD

**Issue by erikyuzwa** [copyblogger/genesis-portfolio-pro#11]
I can't believe how great this plugin is -- never found it until today. Going through the source to determine how to increase the default number of portfolio items being displayed, but can't find any hardcoded reference to `3`. 
Any suggestions on where I'd need to make this change would be fantastic.

**Comment by NicktheGeek** [comment]
It uses the default setting in the settings > reading page of your WordPress install. It is possible to alter the default posts per page apart from that setting but it requires using the pre_get_posts action to alter the main WP query for the portfolio.

Here is a really good tutorial on how to do that in general, it isn't specific to this post type but the post per page example does show how to do this for a post type archive, which should be very helpful
http://www.billerickson.net/customize-the-wordpress-query/#example-posts-per-page

**Comment by erikyuzwa** [comment]
most excellent thanks @NicktheGeek - worked like a charm. Thanks for the extra link - will give me more to dig into. 👍
