### ISSUE TITLE
Plugin Attribution change

### ISSUE THREAD

**Issue by jaygidwitz** [copyblogger/genesis-portfolio-pro#14]
We are changing the attribution and URI on the plugins to point to StudioPress.

This plugin is currently attributed to copyblogger, it should be changed to StudioPress.

<img width="788" alt="screenshot 2017-03-09 10 39 12" src="https://cloud.githubusercontent.com/assets/3248407/23765046/a86558f2-04b4-11e7-9703-38f0623ff29a.png">

**Comment by dreamwhisper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Portfolio Pro](https://trello.com/c/l4QIUKcN/9-genesis-portfolio-pro)

**Comment by nickcernis** [comment]
@NicktheGeek Should it be `StudioPress` rather than `studiopress` to match our other plugins?

Screenshot from `release/1.1`:

<img width="838" alt="plugins_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29659906-9265de6e-88b7-11e7-9e91-8fa24d97149d.png">

**Comment by NicktheGeek** [comment]
updated.

**Comment by nickcernis** [comment]
Confirmed:

<img width="976" alt="plugins_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29667491-821da466-88d4-11e7-98a6-1eacdfab1527.png">
