### ISSUE TITLE
Namespace 

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-portfolio-pro#2]
We should namespace the portfolio_columns function so it doesn't cause a fatal error if someone tries to activate the plugin with a theme like an older version of Executive that also had no namespacing on the function.

```php
add_filter( 'manage_taxonomies_for_portfolio_columns', 'portfolio_columns' );
/**
 * Add Portfolio Type Taxonomy to columns
 *
 * @since 0.1.0
 *
 */
function portfolio_columns( $taxonomies ) {

    $taxonomies[] = 'portfolio-type';
    return $taxonomies;

}
```

**Comment by NicktheGeek** [comment]
added the name space. Closing
