### ISSUE TITLE
Add posts per page setting for portfolio Archives

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/genesis-portfolio-pro#6]
Include a posts per page setting for Portfolio archives so it can be set independently from the standard setting.

**Comment by dreamwhisper** [comment]
Spec:
- Add setting to set the number of posts per page for archives/taxonomy archives
- Default is Settings > Reading > Posts per page
- Needs filter to set the default on theme activation

**Comment by carasmo** [comment]
+1

**Comment by dreamwhisper** [comment]
@NicktheGeek I'm not sure how to handle this, but if someone has the plugin, it would be great not to change their current posts per page on update. So, maybe the default needs to just be what is currently set as posts per page.

Then, the filter can be used to update it on new theme activation.

**Comment by NicktheGeek** [comment]
@dreamwhisper it will probably bear some testing, but I've coded this so that the setting defaults to the option in the reading settings. It will require intentionally changing it to alter the value, so it won't affect it until the setting is changed.

**Comment by NicktheGeek** [comment]
@dreamwhisper I've published the release candidate branch. `release/1.1` if you want to give it a test. It just includes the 3 issues here https://github.com/copyblogger/genesis-portfolio-pro/milestone/1

**Comment by dreamwhisper** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Genesis Portfolio Pro](https://trello.com/c/l4QIUKcN/9-genesis-portfolio-pro)

**Comment by nickcernis** [comment]
@NicktheGeek I think this:

~~~php
if ( ! $query->is_archive( 'portfolio' ) && ! $query->is_tax( 'portfolio-type' ) ) {
	return;
}
~~~

Needs to be this:

~~~php
if ( ! $query->is_post_type_archive( 'portfolio' ) && ! $query->is_tax( 'portfolio-type' ) ) {
	return;
}
~~~

- https://developer.wordpress.org/reference/classes/wp_query/is_post_type_archive/
- https://developer.wordpress.org/reference/classes/wp_query/is_archive/ (takes no arguments)

At the moment the new setting works but it is affecting regular post category archives too:

<img width="449" alt="archive_settings_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29663540-854bd380-88c3-11e7-857f-e65bd6563951.png">

<img width="594" alt="portfolio_items" src="https://user-images.githubusercontent.com/647669/29663567-a25538f4-88c3-11e7-89e1-a564f23aee65.png">

<img width="604" alt="portfolio_types_flowers" src="https://user-images.githubusercontent.com/647669/29663552-944f37fa-88c3-11e7-8223-9b89035bc1a2.png">

<img width="643" alt="reading_settings_ _wp_test_ _wordpress" src="https://user-images.githubusercontent.com/647669/29663665-2628bec6-88c4-11e7-8db7-cc3a54c35545.png">

<img width="948" alt="category__1" src="https://user-images.githubusercontent.com/647669/29663713-691b9b54-88c4-11e7-8fa0-379b6ac3d463.png">

**Comment by NicktheGeek** [comment]
updated

**Comment by nickcernis** [comment]
Confirmed:

<img width="1262" alt="category__1_and_portfolio_items_and_portfolio_types_flowers" src="https://user-images.githubusercontent.com/647669/29667711-565ed1a0-88d5-11e7-963f-06723baa28ff.png">
